alg_name: "RHOEDIT"
model_name: "Qwen/Qwen2.5-7B-Instruct"
device: 1

layers: [15, 16, 17, 18, 19]
num_steps: 25
batch_size: 32
max_length: 40
lr: 5e-4
weight_decay: 0
kl_factor: 0
norm_constraint: false

objective_optimization: "target_new"
rewrite_module_tmp: "model.layers.{}.mlp.down_proj.weight"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
model_parallel: false
mom2_dataset: "wikipedia"
mom2_n_samples: 10000
mom2_dtype: "float32"
task_mom2_dataset: "wiki_big_edit_3k"
task_mom2_n_samples: 3000
task_dtype: "float32"

newton_damping:  1e-5
soft_lambda: 1